### ISSUE TITLE
Uglify Writer error

### ISSUE THREAD

**Issue by devotox** [DockYard/ember-service-worker#157]
```
Build Error (Config)

ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
```

After disabling and enabling every plugin 1 by 1 I have found that this plugin causes the above error

**Comment by devotox** [comment]
```
=================================================================================

ENV Summary:

  TIME: Fri Oct 11 2019 13:01:22 GMT+0100 (British Summer Time)
  TITLE: ember
  ARGV:
  - /Users/devonte/.nvm/versions/node/v10.16.3/bin/node
  - /usr/local/bin/ember
  - build
  - -e
  - production
  EXEC_PATH: /Users/devonte/.nvm/versions/node/v10.16.3/bin/node
  TMPDIR: /var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T
  SHELL: /usr/local/bin/fish
  PATH:
  - /Users/devonte/.gem/ruby/2.6.0/bin
  - /usr/local/Cellar/ruby/2.6.2/bin/
  - /usr/local/Cellar/ruby/2.6.2/lib/ruby/gems/2.6.0/bin
  - /usr/local/lib/ruby/gems/2.6.0/bin
  - /Users/devonte/go/bin
  - /usr/local/opt/gnu-sed/libexec/gnubin
  - /Users/devonte/.nvm/versions/node/v10.16.3/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 1573326848
  TOTALMEM: 17179869184
  UPTIME: 3646120
  LOADAVG: 13.677734375,12.8330078125,9.8017578125
  CPUS:
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.39.2
  - node: 10.16.3
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Config.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/lib/config.js:37:27)
    at resolve (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/wrappers/transform-node.js:68:45)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/wrappers/transform-node.js:53:16)
    at Promise.resolve.then.then.then (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/builder.js:99:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
  - errorMessage: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
        at Config
-~- created here: -~-
    at new Plugin (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli-plugin/index.js:7:31)
    at new Config (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/lib/config.js:16:5)
    at Class.treeForServiceWorker (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/index.js:20:22)
    at ServiceWorkerBuilder._treeForPlugin (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:54:35)
    at plugins.reduce (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:33:29)
    at Array.reduce (<anonymous>:null:null)
    at ServiceWorkerBuilder._treesForPlugins (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:32:25)
    at ServiceWorkerBuilder.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:27:22)
    at Class.postprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/index.js:81:50)
    at projectOrAddon.addons.reduce (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>:null:null)
    at addonProcessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at module.exports (/Users/devonte/Documents/Devonte/zenunu/ember-cli-build.js:334:13)
    at Builder.readBuildFile (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
        at Config
-~- created here: -~-
    at new Plugin (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli-plugin/index.js:7:31)
    at new Config (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/lib/config.js:16:5)
    at Class.treeForServiceWorker (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/index.js:20:22)
    at ServiceWorkerBuilder._treeForPlugin (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:54:35)
    at plugins.reduce (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:33:29)
    at Array.reduce (<anonymous>:null:null)
    at ServiceWorkerBuilder._treesForPlugins (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:32:25)
    at ServiceWorkerBuilder.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/lib/service-worker-builder.js:27:22)
    at Class.postprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker/index.js:81:50)
    at projectOrAddon.addons.reduce (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>:null:null)
    at addonProcessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at module.exports (/Users/devonte/Documents/Devonte/zenunu/ember-cli-build.js:334:13)
    at Builder.readBuildFile (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: Config
  - originalErrorMessage: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
  - stack: Error: ENOENT: no such file or directory, open '/var/folders/zp/9skf2wx96b37hdk3_rbd457m0000gn/T/broccoli-26206cJ2f089zeRMo/out-1093-uglify_writer/app'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Config.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/ember-service-worker-index/lib/config.js:37:27)
    at resolve (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/wrappers/transform-node.js:68:45)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/wrappers/transform-node.js:53:16)
    at Promise.resolve.then.then.then (/Users/devonte/Documents/Devonte/zenunu/node_modules/broccoli/dist/builder.js:99:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)


=================================================================================
```

**Comment by devotox** [comment]
Actually i think it is ESW Index looking for a file `app` that is not there
